### ISSUE TITLE
support multiple version of specifications

### ISSUE THREAD

**Issue by davidB** [cdevents/sdk-rust#16]
The crate should support to read/write multiple version of cdevents'spec (and version of message).

- the different version should be supported simultaneously (a reader should be backward compatible)
- the different version could be behind feature flag, if a consumer want to only work with one or few specific versions, by default all version are enabled

**Comment by afrittoli** [comment]
Thanks @davidB. I agree that the SDK should be able to parse older versions of CDEvents.
In terms of producing events, my initial thought was that a specific version of the SDK should only be able to produce events for the corresponding version - this is how the golang SDK is currently implemented.

If a producer needs to support consumers on different versions, I see how being able to produce multiple versions with the same SDK would come in handy, so that's something we should consider adding to other SDKs too.
